apiVersion: v1
kind: Service
metadata:
  name: feedback-app-service
spec:
  selector:
    app: feedback-app
  type: LoadBalancer
  ports:
    - port: 80          # external port (what users access)
      targetPort: 8000  # internal Gunicorn port
